# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "rabbitmq01" do |rabbitmq|
    config.vm.network "private_network", ip: "192.168.33.33"
  end

  config.vm.define "elasticsearch01" do |elasticsearch|
    config.vm.network "private_network", ip: "192.168.33.43"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/site.yml"
    ansible.groups = {
      "rabbitmq"      => ["rabbitmq01"],
      "elasticsearch" => ["elasticsearch01"]
    }
  end
end
